language: node_js
dist: trusty
sudo: required

node_js:
  - "stable"

cache:
  directories:
    - node_modules # NPM packages

install:
  - npm install

jobs:
  include:
    - stage: lint
      - npm run lint
    - stage: build
      script:
        - npm run build
        - echo "Removing unwanted files"
        - rm -vf _book/.travis.yml
        - rm -vf _book/*.yml
        - rm -vf _book/*.md
        - rm -vf _book/*.sh
    - stage: deploy
      - provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: _book
        target_branch: gh-pages
stages:
  - lint
  - build
    if: branch = master
  - deploy
    if: branch = master